Resources:
  # Separate API Gateway for Admin
  AdminRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ${self:service}-${self:provider.stage}-admin-api
      Description: Admin API for CRM system
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Analytics resource
  AdminApiAnalyticsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AdminRestApi
      ParentId: !GetAtt AdminRestApi.RootResourceId
      PathPart: analytics

  AdminApiAnalyticsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiAnalyticsResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DailyAnalyticsLambdaFunction.Arn}/invocations"

  AdminApiAnalyticsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiAnalyticsResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Leads resource
  AdminApiLeadsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AdminRestApi
      ParentId: !GetAtt AdminRestApi.RootResourceId
      PathPart: leads

  AdminApiLeadIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AdminRestApi
      ParentId: !Ref AdminApiLeadsResource
      PathPart: "{lead_id}"

  AdminApiLeadDetailsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiLeadIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetLeadDetailsLambdaFunction.Arn}/invocations"

  AdminApiLeadDetailsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiLeadIdResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Spam resource
  AdminApiSpamResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AdminRestApi
      ParentId: !GetAtt AdminRestApi.RootResourceId
      PathPart: spam

  AdminApiSpamMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiSpamResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetSpamActivitiesLambdaFunction.Arn}/invocations"

  AdminApiSpamOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiSpamResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Spam Users resource
  AdminApiSpamUsersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AdminRestApi
      ParentId: !Ref AdminApiSpamResource
      PathPart: users

  AdminApiSpamUsersMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiSpamUsersResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetSpamUsersLambdaFunction.Arn}/invocations"

  AdminApiSpamUsersOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AdminRestApi
      ResourceId: !Ref AdminApiSpamUsersResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  AdminApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - AdminApiAnalyticsMethod
      - AdminApiAnalyticsOptionsMethod
      - AdminApiLeadDetailsMethod
      - AdminApiLeadDetailsOptionsMethod
      - AdminApiSpamMethod
      - AdminApiSpamOptionsMethod
      - AdminApiSpamUsersMethod
      - AdminApiSpamUsersOptionsMethod
    Properties:
      RestApiId: !Ref AdminRestApi
      StageName: ${self:provider.stage}

  AdminApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: AdminApiDeployment
    Properties:
      Name: ${self:service}-${self:provider.stage}-admin-api-key
      Description: API Key for Admin Functions
      Enabled: true

  AdminUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: AdminApiDeployment
    Properties:
      UsagePlanName: ${self:service}-${self:provider.stage}-admin-usage-plan
      Description: Usage plan for admin endpoints
      ApiStages:
        - ApiId: !Ref AdminRestApi
          Stage: ${self:provider.stage}
      Throttle:
        RateLimit: 5
        BurstLimit: 10
      Quota:
        Limit: 1000
        Period: DAY

  AdminUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref AdminApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref AdminUsagePlan

  AdminAnalyticsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DailyAnalyticsLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AdminRestApi}/*/*"

  AdminLeadDetailsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetLeadDetailsLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AdminRestApi}/*/*"

  AdminSpamActivitiesLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetSpamActivitiesLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AdminRestApi}/*/*"

  AdminSpamUsersLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetSpamUsersLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AdminRestApi}/*/*"

Outputs:
  AdminApiUrl:
    Description: "Admin API URL"
    Value: !Sub "https://${AdminRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
  
  AdminAnalyticsUrl:
    Description: "Admin Analytics API URL"
    Value: !Sub "https://${AdminRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/analytics"

  AdminLeadDetailsUrl:
    Description: "Admin Lead Details API URL"
    Value: !Sub "https://${AdminRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/leads/{lead_id}"

  AdminSpamActivitiesUrl:
    Description: "Admin Spam Activities API URL"
    Value: !Sub "https://${AdminRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/spam"
  
  AdminSpamUsersUrl:
    Description: "Admin Spam Users API URL"
    Value: !Sub "https://${AdminRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/spam/users"
  
  AdminApiKey:
    Description: "Admin API Key"
    Value: !Ref AdminApiKey
