service: pandasdb-crm-comm-backoffice

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  
  environment:
    # Import table names from main stack
    LEADS_TABLE: 
      Fn::ImportValue: ${self:custom.mainStackName}-LeadsTable
    CONTACT_METHODS_TABLE:
      Fn::ImportValue: ${self:custom.mainStackName}-ContactMethodsTable
    CONTACT_METHOD_SETTINGS_TABLE:
      Fn::ImportValue: ${self:custom.mainStackName}-ContactMethodSettingsTable
    ACTIVITIES_TABLE:
      Fn::ImportValue: ${self:custom.mainStackName}-ActivitiesTable
    ACTIVITY_CONTENT_TABLE:
      Fn::ImportValue: ${self:custom.mainStackName}-ActivityContentTable
    SPAM_ACTIVITIES_TABLE:
      Fn::ImportValue: ${self:custom.mainStackName}-SpamActivitiesTable
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: 
            - Fn::ImportValue: ${self:custom.mainStackName}-LeadsTableArn
            - Fn::ImportValue: ${self:custom.mainStackName}-ContactMethodsTableArn
            - Fn::ImportValue: ${self:custom.mainStackName}-ContactMethodSettingsTableArn
            - Fn::ImportValue: ${self:custom.mainStackName}-ActivitiesTableArn
            - Fn::ImportValue: ${self:custom.mainStackName}-ActivityContentTableArn
            - Fn::ImportValue: ${self:custom.mainStackName}-SpamActivitiesTableArn
            - Fn::Sub:
              - "${LeadsTableArn}/index/*"
              - LeadsTableArn:
                  Fn::ImportValue: ${self:custom.mainStackName}-LeadsTableArn
            - Fn::Sub:
              - "${ContactMethodsTableArn}/index/*"
              - ContactMethodsTableArn:
                  Fn::ImportValue: ${self:custom.mainStackName}-ContactMethodsTableArn
            - Fn::Sub:
              - "${ActivitiesTableArn}/index/*"
              - ActivitiesTableArn:
                  Fn::ImportValue: ${self:custom.mainStackName}-ActivitiesTableArn
            - Fn::Sub:
              - "${SpamActivitiesTableArn}/index/*"
              - SpamActivitiesTableArn:
                  Fn::ImportValue: ${self:custom.mainStackName}-SpamActivitiesTableArn

functions:
  # Lead Management
  createLead:
    handler: handlers/create_lead.lambda_handler
    events:
      - http:
          path: api/leads
          method: post
          cors: true
          private: true  # Requires API key
  
  listLeads:
    handler: handlers/list_leads.lambda_handler
    events:
      - http:
          path: api/leads
          method: get
          cors: true
          private: true  # Requires API key
  
  getLeadDetails:
    handler: handlers/get_lead_details.lambda_handler
    events:
      - http:
          path: api/lead/{lead_id}
          method: get
          cors: true
          private: true  # Requires API key
  
  # Analytics
  getDailyAnalytics:
    handler: handlers/get_daily_analytics.lambda_handler
    events:
      - http:
          path: api/analytics/daily
          method: get
          cors: true
          private: true  # Requires API key
  
  getSpamActivities:
    handler: handlers/get_spam_activities.lambda_handler
    events:
      - http:
          path: api/spam/activities
          method: get
          cors: true
          private: true  # Requires API key
  
  getSpamUsers:
    handler: handlers/get_spam_users.lambda_handler
    events:
      - http:
          path: api/spam/users
          method: get
          cors: true
          private: true  # Requires API key

  removeSpamActivities:
    handler: handlers/remove_spam_activities.lambda_handler
    events:
      - http:
          path: api/spam/activities/{lead_id}
          method: delete
          cors: true
          private: true  # Requires API key

custom:
  mainStackName: pandasdb-crm-comm-${self:provider.stage}
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

resources:
  Resources:
    # API Key for Backoffice Access
    BackofficeApiKey:
      Type: AWS::ApiGateway::ApiKey
      Properties:
        Name: ${self:service}-${self:provider.stage}-api-key
        Description: Auto-generated API Key for Backoffice Access
        Enabled: true
        Value: !Sub '${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-${self:provider.stage}'

    # Usage Plan for Rate Limiting and API Key Management
    BackofficeUsagePlan:
      Type: AWS::ApiGateway::UsagePlan
      Properties:
        UsagePlanName: ${self:service}-${self:provider.stage}-usage-plan
        Description: Usage plan for Backoffice API with rate limiting
        ApiStages:
          - ApiId: !Ref ApiGatewayRestApi
            Stage: ${self:provider.stage}
        Throttle:
          RateLimit: 100      # 100 requests per second
          BurstLimit: 200     # 200 concurrent requests max
        Quota:
          Limit: 10000        # 10000 requests per day
          Period: DAY

    # Link API Key to Usage Plan
    BackofficeUsagePlanKey:
      Type: AWS::ApiGateway::UsagePlanKey
      DependsOn:
        - BackofficeApiKey
        - BackofficeUsagePlan
      Properties:
        KeyId: !Ref BackofficeApiKey
        KeyType: API_KEY
        UsagePlanId: !Ref BackofficeUsagePlan

    # S3 Bucket for Backoffice Frontend
    BackofficeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
              AllowedOrigins: ['*']
              MaxAge: 3600
    
    # S3 Bucket Policy for Public Read
    BackofficeBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref BackofficeBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "${BackofficeBucket}/*"
    
    # CloudFront Origin Access Identity
    BackofficeOriginAccessIdentity:
      Type: AWS::CloudFront::OriginAccessIdentity
      Properties:
        OriginAccessIdentityConfig:
          Comment: !Sub 'OAI for ${self:service}-${self:provider.stage}'
    
    # CloudFront Distribution for Global CDN
    BackofficeDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: !Sub 'CDN for ${self:service}-${self:provider.stage}'
          DefaultRootObject: index.html
          PriceClass: PriceClass_100  # Use only North America and Europe edge locations
          
          Origins:
            - Id: BackofficeS3Origin
              DomainName: !GetAtt BackofficeBucket.RegionalDomainName
              S3OriginConfig:
                OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${BackofficeOriginAccessIdentity}'
          
          DefaultCacheBehavior:
            TargetOriginId: BackofficeS3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # Managed-CORS-S3Origin
          
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
              ErrorCachingMinTTL: 300
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
              ErrorCachingMinTTL: 300
          
          HttpVersion: http2
          IPV6Enabled: true

  Outputs:
    BackofficeUrl:
      Description: "Backoffice Frontend URL"
      Value: !Sub "https://${BackofficeDistribution.DomainName}"
      Export:
        Name: ${self:service}-${self:provider.stage}-BackofficeUrl
    
    BackofficeBucket:
      Description: "S3 Bucket for Backoffice Frontend"
      Value: !Ref BackofficeBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-BackofficeBucket
    
    BackofficeDistributionId:
      Description: "CloudFront Distribution ID"
      Value: !Ref BackofficeDistribution
      Export:
        Name: ${self:service}-${self:provider.stage}-BackofficeDistributionId
    
    BackofficeApiUrl:
      Description: "Backoffice API URL"
      Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
      Export:
        Name: ${self:service}-${self:provider.stage}-BackofficeApiUrl

    BackofficeApiKey:
      Description: "Auto-generated API Key for Backoffice Access"
      Value: !Ref BackofficeApiKey
      Export:
        Name: ${self:service}-${self:provider.stage}-BackofficeApiKey

    BackofficeApiKeyValue:
      Description: "API Key Value for Frontend Configuration"
      Value: !Sub '${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-${self:provider.stage}'
      Export:
        Name: ${self:service}-${self:provider.stage}-BackofficeApiKeyValue

plugins:
  - serverless-python-requirements
